name: Navegador Directo Cloudflare
on:
  workflow_dispatch:

jobs:
  run-browser:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciar Entorno Web
        run: |
          # 1. Levanta el navegador virtual
          docker run -d -p 6080:80 --security-opt seccomp=unconfined dorowu/ubuntu-desktop-lxde-vnc
          
          echo "=========================================================="
          echo "INSTALANDO FILTRO SEGURO CLOUDFLARE..."
          echo "=========================================================="
          
          # 2. Descarga el conector oficial de Cloudflare
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          
          echo "=========================================================="
          echo "GENERANDO ENLACE DIRECTO SIN ADVERTENCIAS..."
          echo "=========================================================="
          
          # 3. Crea el túnel directo al navegador virtual
          ./cloudflared tunnel --url http://localhost:6080
