name: Navegador Libre Pinggy
on:
  workflow_dispatch:

jobs:
  run-browser:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciar Entorno Web
        run: |
          # 1. Levanta el navegador virtual
          docker run -d -p 6080:80 --security-opt seccomp=unconfined dorowu/ubuntu-desktop-lxde-vnc
          
          echo "=========================================================="
          echo "GENERANDO ENLACE SEGURO CON PINGGY..."
          echo "=========================================================="
          
          # 2. Crea un túnel SSH retransmitiendo el navegador
          ssh -p 443 -R0:localhost:6080 -o StrictHostKeyChecking=no a.pinggy.io
